package com.acme;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.ImportResource;
import org.springframework.stereotype.Component;

/**
 * Standard main class for Spring, generated by Spring template
 */
@SpringBootApplication
//@ComponentScan
@ImportResource("classpath:applicationContext.xml")
public class Application {
    /**
     * Maintain reference to Spring's "context" for the application
     */
    private static ApplicationContext applicationContext = null;
    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    /**
     * Obtain  initialized reference to Spring's "context" for the application
     * @return Spring's context for the application
     */
    public static ApplicationContext getApplicationContext()
    {
        if (applicationContext == null)
        {
            applicationContext = new AnnotationConfigApplicationContext(Application.class);
        }
        return applicationContext;
    }
}
